### ISSUE TITLE
Azithromycin vs Salmonella spp. 

### ISSUE THREAD

**Issue by send2dan** [msberends/AMR#66] opened 2022-08-14 08:09 UTC
I have analysed all blood culture AST results 2019 - 2022 at Newcastle Hospitals NHS Foundation Trust RE: Azithromycin vs. Salmonella

Two Salmonella spp. isolates were reported as susceptible ("S"), which the [AMR](https://msberends.github.io/AMR/articles/AMR.html) package flagged as a discrepant result.

The [EUCAST Expected Resistant Phenotypes](https://www.eucast.org/fileadmin/src/media/PDFs/EUCAST_files/Expert_Rules/2022/Expected_Resistant_Phenotypes_v1.1_20220325.pdf) state that the "Enterobacterales and Aeromonas spp. are ... expected to be resistant to benzylpenicillin, glycopeptides, lipoglycopeptides, fusidic acid, macrolides (with some exceptions), lincosamides, streptogramins, rifampicin, and oxazolidinones". 

Regarding the macrolide-related exceptions, [EUCAST Expected Resistant Phenotypes](https://www.eucast.org/fileadmin/src/media/PDFs/EUCAST_files/Expert_Rules/2022/Expected_Resistant_Phenotypes_v1.1_20220325.pdf) state that "Azithromycin is effective in vivo for the treatment of typhoid/paratyphoid fever and erythromycin may be used to treat travellers’ diarrhoea.

I suspect the [AMR](https://msberends.github.io/AMR/articles/AMR.html) package flagged the results as discrepant because the organism was entered in the LIMS as "Salmonella spp.", rather than "S. typhi" or "S. paratyphi". Strictly speaking, only "S. typhi" and "S. paratyphi" should be reported as susceptible to azithromycin. 

Are these kinds of nuances something you're interested in?

**Comment by msberends** [comment] 2022-08-14 08:55
Thanks so much for reporting! These are definitely things we are interested in! 

I think a part of this problem is how *S. typhi* and *S. paratyphi* are treated by the AMR package, which relies on LPSN for bacterial taxonomy. Reading [the *Salmonella* overview at LPSN](https://lpsn.dsmz.de/genus/salmonella) it appears that in 2000, Ezaki et al. edited these two species to make them synonyms of *S. enterica* ([PMID 10758909](https://pubmed.ncbi.nlm.nih.gov/10758909/)).

I’m not sure how EUCAST handles this. If there are guidelines available (such as EUCAST) that split them into separate species, then currently the AMR package will never be able to apply these guidelines, since currently *S. typhi* and *S. paratyphi* are both coerced to *S. enterica* following LPSN:

```r
library(AMR)
mo_name("Salmonella paratyphi")
#> ℹ Salmonella paratyphi (Ezaki et al., 2000) was renamed back to Salmonella enterica (Le Minor et al., 1987) [B_SLMNL_ENTR]
#> [1] "Salmonella enterica"
```

I understand the clinical relevance though, so let me read in on EUCAST to comprehend the nuance better. If need be, we could add *S. typhi* and *S. paratyphi* by means of exception. 

Another difficulty is what you say here:

> Regarding the macrolide-related exceptions, [EUCAST Expected Resistant Phenotypes](https://www.eucast.org/fileadmin/src/media/PDFs/EUCAST_files/Expert_Rules/2022/Expected_Resistant_Phenotypes_v1.1_20220325.pdf) state that "Azithromycin is effective in vivo for the treatment of typhoid/paratyphoid fever and erythromycin may be used to treat travellers’ diarrhoea.

That’s of course true, but the LIMS data is not about in vivo results, it’s about in vitro results. So, although I also understand the clinical point of view, it’s highly debatable to then say “let’s overwrite the in vitro results with what could be working in vivo to S”. If some labs would *report* them S, that’s fine. But not all might and this is a very confusing part in the EUCAST guideline, also when it comes to reproducibility of results and integrity of data. How do you look at this?

**Comment by msberends** [comment] 2022-08-14 09:04
There’s a lot of scientific debate on regarding the two *Salmonella* species as *S. enterica*. This is from a list of comments on an IJSEM paper (Opinion 80):

Tindall BJ, Grimont PA, Garrity GM, Euzeby JP. Nomenclature and taxonomy of the genus Salmonella. Int J Syst Evol Microbiol 2005; 55:521-524. [PMID 15653930](https://www.ncbi.nlm.nih.gov/pubmed/15653930)

Speaking about confusion 😅

**Comment by msberends** [comment] 2022-12-29 08:25
We now added all 1,516 city-like serovars of S. enterica, such as S. Paratyphi (A, B and C). 

So, we can now update the interpretation for EUCAST. This will be done next week or so!

**Comment by theanita1** [comment] 2023-02-06 07:06
Hi Dr Matthijs

> We now added all 1,516 city-like serovars of S. enterica, such as S. Paratyphi (A, B and C).
> 
> So, we can now update the interpretation for EUCAST. This will be done next week or so!

Following on from this update, it should be that all subtypes are coded individually correct? 

I can see in my dataset that Paratyphi and other subtypes are being identified, but not Typhi: 
![image](https://user-images.githubusercontent.com/11519951/216904743-cbd00ddc-d751-4f75-86aa-3faea28a5619.png)

However I know (having looked at the microorganisms dataframe) that you've got a separate code for it

When I run the as.mo function this is our output:
![image](https://user-images.githubusercontent.com/11519951/216905155-67060390-3e0f-4c59-bead-22d282bf82b2.png)

My current work around is to use recode_if, but it should be automatically coded as SLMNL_TYPH no?

**Comment by theanita1** [comment] 2023-02-06 07:22
Hi Dr Mathijs

> We now added all 1,516 city-like serovars of S. enterica, such as S. Paratyphi (A, B and C).
> 
> So, we can now update the interpretation for EUCAST. This will be done next week or so!

So from this update it should flag all subspecies with their own code right?

It's working for most of them in my dataset, but some of them aren't being captured:
![image](https://user-images.githubusercontent.com/11519951/216908431-6f061988-7866-4274-b2b4-fd00ea704c1e.png)

When I run the as.mo function this is what I get:
![image](https://user-images.githubusercontent.com/11519951/216908557-5c177d1e-eca7-42f4-a869-bd795a9fcee9.png)

I'm currently doing a manual "recode_if" work around but thought I'd flag

**Comment by msberends** [comment] 2023-02-06 08:08
Ah, it seems S. typhi and S. Typhi both exist. Thanks for letting me know! I’ll fix it right away.

**Comment by msberends** [comment] 2023-02-10 16:11
Fixed in `main`!

**Closed as completed by msberends** 2023-02-10 16:11 UTC
Labels: enhancement
